### ISSUE TITLE
1::128

### ISSUE THREAD

**Issue by rorxor** [euwbah/musescore-xen-tuner#5]
Hi there

I've been playing around with harmonics 1-128 in my DAW, but I'd like to learn how I might notate it, and also use musescores new sound library along with articulations for a more satisfying compositional experience.

Can anyone give me any pointers? Can Xen Tuner achieve this?

Thanks!

**Comment by euwbah** [comment]
Regarding the playback using MuseSounds, it is not supported for 2 reasons

- This plugin only works on MS 3.6, not the newer MS4. MS4 plugin dev is still [not ready](https://github.com/musescore/MuseScore/issues/17474) to port this complex plugin over.
- MuseSounds still has a [bug](https://github.com/musescore/MuseScore/issues/18036) when playing back microtuned notes

As for the engraving/notating side of your question:

There's quite a few different ways to notate the harmonics, it depends on what you want. Xen Tuner can implement almost all of them except Functional Just Notation (which requires quite a fair bit of code to be added, so I didn't have time to get to that yet)

The most "traditional" way would be to use [HEJI](https://github.com/euwbah/musescore-xen-tuner/tree/master/tunings/heji), which only supports up to the prime 41. For higher primes you will need to modify the tuning config .txt yourself and substitute other non-standard symbols (musescore doesn't have the updated list of higher-limit HEJI symbols yet), or resort to using [text based JI ratio annotations](https://github.com/euwbah/musescore-xen-tuner/tree/master#2-fingerings-to-denote-ji-intervals) or [cent offset annotations](https://github.com/euwbah/musescore-xen-tuner/tree/master#3-fingerings-to-denote-cent-offsets).

However, since you only want the otonal series, I would recommend just using [text based JI ratio annotations](https://github.com/euwbah/musescore-xen-tuner/tree/master#2-fingerings-to-denote-ji-intervals) all the way, so that it is clearer what harmonic you want. However, this method may be less user-friendly as you can't use the arrow keys to access all the pitches and you will need to manually type in/copy fingerings.

You also have the option of using scordatura, where you represent the overtone series with [custom nominals](https://github.com/euwbah/musescore-xen-tuner/tree/master#simple-example) (e.g. having 128 nominals instead of 7). For an example, you can see how custom nominals are used to achieve [chromatic staves](https://github.com/euwbah/musescore-xen-tuner/tree/master/tunings/chromatic). This method allows you to access all unique notes with the arrow keys.

You can also use 63 edo "NEJI" (near-equal just intonation) to represent the 63 unique (not counting octave equivalences) notes  as edosteps of 63 edo [ups and downs edo generator python script](https://github.com/euwbah/musescore-xen-tuner/blob/master/tunings/updown/generate-edo-updown.py) in conjunction with the [NEJI generator python script](https://github.com/euwbah/musescore-xen-tuner/tree/master/tunings/neji). This method lets you use the arrow keys as well.

You can also use HEWM, which is similar to HEJI, but instead of accidental symbols, you have ASCII text instead. This one goes up to 61-limit JI, then you can use fingering annotations for the higher limit primes.

There's probably a bunch of other ways to notate this, but I can't think of any off the top of my head.

**Comment by rorxor** [comment]
Hi euwbah, thank you for your response wow! I have a certain primodal bent, so the 63edo idea seems very intriguing. I will be exploring these options for a while, thanks again for all the leads. R

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
